### ISSUE TITLE
How to host only the book directory

### ISSUE THREAD

**Issue by un10able** [MichaelCurrin/mdbook-quickstart#2]
Hi, this is clearly a problem with my knowledge but how does one actually make GH pages host only the book directory? It would be good to have that in the docs.

**Comment by fsegurai** [comment]
What I did was to publish the main branch (this operation creates a new branch for GitHub Pages which contains only the book directory), once the pipeline/action has finished the deployment, I changed the GitHub page source branch for the new one 'gh-pages'.

Now, everytime I make a commit on 'main'; it will automatically update the 'gh-pages' branch with the most recent book directory content and since it is the source branch for GitHub pages, it will create a new pipeline/action to deploy the book content because GitHub has detected a change in the 'gh-pages' branch.

Let me know if that helped you @un10able

**Comment by MichaelCurrin** [comment]
Sorry for not seeing this issue.

md-book outputs a directory `book`

Then in the CI flow with GH Actions 
https://github.com/MichaelCurrin/mdbook-quickstart/blob/main/.github/workflows/main.yml

...the contents of `book` are committed on the `gh-pages` directory at the root by this setup. No action needed. https://github.com/MichaelCurrin/mdbook-quickstart/tree/gh-pages

**Comment by MichaelCurrin** [comment]
I added notes here - let me know if that is sufficient? 

https://github.com/MichaelCurrin/mdbook-quickstart/blob/main/docs/deploy.md
